
# Get NodeJs
FROM node:lts-alpine

# WORKDIR /usr/local/app

COPY ./dist ./dist
COPY ./node_modules ./node_modules
COPY ./angular.json .
COPY ./package.json .
COPY ./package-lock.json .

CMD [ "node", "dist/nahu-dev-personal-site/server/proxy-server.js"]

EXPOSE 4200
