
# Get NodeJs
FROM node:lts-alpine

WORKDIR /usr/local/app

COPY ./dist ./dist

RUN npm install express
RUN npm install compression
RUN npm install firebase

CMD [ "node", "dist/server/proxy-server.js"]

EXPOSE 4200
